title: Thomas Larsen
description: My experiences and portfolio
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
header_pages:
  - index.md
  - flight-path.md
